---

- name: "create deploy dir {{ cockroachdb_remote_install_dir }}"
  file: state='directory' path="{{ cockroachdb_remote_install_dir }}"

- name: "copy {{ cockroachdb_download_dir }}/{{ cockroachdb_pkg }}/{{ cockroachdb_product }} to {{ cockroachdb_remote_install_dir }}/"
  copy: src="{{ cockroachdb_download_dir }}/{{ cockroachdb_pkg}}/{{ cockroachdb_product }}" dest="{{ cockroachdb_remote_install_dir }}/{{ cockroachdb_product }}" mode='u=xrw,g=xr,o=r'

- name: "create certs deploy dir {{ cockroachdb_remote_install_dir }}/certs"
  file: state='directory' path="{{ cockroachdb_remote_install_dir }}/certs"
  when: cockroachdb_security_mode == 'secure'

- name: "copy ca from {{ cockroachdb_local_certs_dir }}/ca/ca.crt to {{ cockroachdb_remote_install_dir }}/certs"
  copy: src="{{ cockroachdb_local_certs_dir }}/ca/ca.crt" dest="{{ cockroachdb_remote_install_dir }}/certs/"
  when: cockroachdb_security_mode == 'secure'

- name: "copy certs from {{ cockroachdb_local_certs_dir }}/node/* to {{ cockroachdb_remote_install_dir }}/certs"
  copy: src="{{ item }}" dest="{{ cockroachdb_remote_install_dir }}/certs/"
  with_fileglob:
    - "{{ cockroachdb_local_certs_dir }}/{{ hostvars[inventory_hostname] }}/*"
  when: cockroachdb_security_mode == 'secure'

#- name: "copy certs from {{ cockroachdb_local_certs_dir }}/node/* to {{ cockroachdb_remote_certs_dir }}/"
#  copy: src="{{ item }}" dest="{{ cockroachdb_remote_certs_dir }}/"
#  with_fileglob:
#    - "{{ cockroachdb_local_certs_dir }}/{{ groups['cockroachdb-server'] | intersect( groups[ vars['target_env'] ]) | intersect( [hostvars[inventory_hostname]] ) }}/*"
