---

#- name: 'add certbot apt repo'
#  apt_repository:
#    repo: ppa:certbot/certbot
#
#- name: 'install nginx and certbot digitalocean plugin'
#  package:
#    name: "{{ item }}"
#    state: present
#  with_items:
#  - "nginx"
#  - "python3-certbot-dns-digitalocean"
#  - "python3-certbot-nginx"

- name: "register {{ domain }} to {{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}"
  digital_ocean_domain:
    state: present
    name: "{{ domain }}"
    ip: "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}"
    oauth_token: "{{ lookup('env','DO_API_TOKEN') }}"

- name: 'install nginx'
  package:
    name: "{{ item }}"
    state: present
  with_items:
  - 'nginx'
  - 'python3-passlib'

- htpasswd:
    path: "{{ htpasswd_path }}"
    name: 'hademo'
    password: "{{hademo_password}}"
    owner: root
    group: www-data
    mode: 0640

- name: "deactivate nginx default site"
  file: state='absent' path="/etc/nginx/sites-enabled/default"

- name: 'extrapolate nginx config'
  template: src='{{ domain }}.j2' dest="/etc/nginx/sites-available/{{ domain }}"

- name: 'link sites-available sites-enabled'
  file: state='link' src="/etc/nginx/sites-available/{{ domain }}" dest="/etc/nginx/sites-enabled/{{ domain }}"

- name: 'restart nginx'
  service: name='nginx' enabled='yes' state='restarted'

- name: 'wait for port 80 to come up'
  wait_for: port="80" delay='1' timeout='5'
#
#- name: 'add certbot apt repo'
#  apt_repository:
#    repo: ppa:certbot/certbot
#
#- name: 'install nginx and certbot digitalocean plugin'
#  package:
#    name: "{{ item }}"
#    state: present
#  with_items:
#  - "python-certbot-nginx"
##  - "python-certbot-dns-digitalocean"
#
#- name: 'issue certificate for {{ domain }}'
#  shell: "echo 'no 2' | certbot --nginx -d {{ domain }} --agree-tos -m 'louis.gueye@gmail.com'"
#
#- name: 'restart nginx'
#  service: name='nginx' enabled='yes' state='restarted'
#
#- name: 'wait for port 80 to come up'
#  wait_for: port="80" delay='1' timeout='5'
